/** NOTE: This file is autogenerated at build time. Your changes will be overwritten! */

import { NetworkResponse } from '../stores/Response';

export const mockResponseForEndpoint = (endpoint: string): NetworkResponse => {
	const uri = endpoint.split(';')[0];
	const normalized = uri.split('/').join('_');
	if (normalized === 'login.json') { return require('../mocks/login.json'); }
	if (normalized === 'mysAlerts.json') { return require('../mocks/mysAlerts.json'); }
	if (normalized === 'refreshVehicles.json') { return require('../mocks/refreshVehicles.json'); }
	if (normalized === 'selectVehicle.json') { return require('../mocks/selectVehicle.json'); }
	if (normalized === 'service_g2_condition_execute.json') { return require('../mocks/service_g2_condition_execute.json'); }
	if (normalized === 'service_g2_engineStart_execute.json') { return require('../mocks/service_g2_engineStart_execute.json'); }
	if (normalized === 'service_g2_engineStop_execute.json') { return require('../mocks/service_g2_engineStop_execute.json'); }
	if (normalized === 'service_g2_lock_execute.json') { return require('../mocks/service_g2_lock_execute.json'); }
	if (normalized === 'service_g2_remoteService_status.json') { return require('../mocks/service_g2_remoteService_status.json'); }
	if (normalized === 'service_g2_unlock_execute.json') { return require('../mocks/service_g2_unlock_execute.json'); }
	return {success: false, errorCode: 'NotImplemented', data: null, dataName: null, endpoint: normalized};
}
